name: sponsorkit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Once a day

permissions:
  contents: write

jobs:
  update-sponsors:
    name: Update sponsors
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install packages
        run: yarn install

      - name: Install packages
        run: yarn install

      - name: Install sharp
        run: SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=linux yarn add sharp --ignore-engines -W -D

      - name: Update sponsors
        run: yarn generate
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: prc5

      - name: Commit
        run: |
          if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name 'Maciej Pyrc'
          git config user.email 'maciekpyrc@gmail.com'
          git add .
          git commit -am 'chore: 🤖 update sponsors'
          git push
